# Generated by Django 3.2.11 on 2022-01-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usersdb',
        ),
    ]
