# Generated by Django 3.2.11 on 2022-01-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220126_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdb',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
