# Generated by Django 3.2.11 on 2022-01-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usersdb_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='pic',
            field=models.FileField(default='new.jpg', null=True, upload_to=''),
        ),
    ]
